### ISSUE TITLE
Investigating using mocha/jest for the tests

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/reps#101]
We are using mochitest to test Reps at the moment. The tests aren't too long to run, but they require having a clone of firefox to be run. It is fine to have this on CI, because we can then launch test on the console for example, but locally it can be a bit cumbersome.

So maybe we could try to use mocha, like we do in the console, to test the components.
We don't really need to have the browser environment for this, since all the reps are React component (and we test them directly by creating the Reps component, instead of evaluating an expression for example).
Since mocha is pretty fast, we could even have those to run as a hook before pushing to origin.

The downside I see to this is that if we do that, the tests wouldn't be ran in TRY, and we could have some issue if there are server-side changes. There's a  filed bug in the console to run mocha in TRY, so maybe this should be blocking this investigation.

**Comment by jasonLaster** [comment]
I'll be adding Jest when I add the Object Inspector
