### ISSUE TITLE
Rename internal props variables to avoid confusion with React props

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/reps#103]
We use "props" as internal variable names in some classes and it is confusing as it can be confused with React's `props`.
- [ ] in array.js to list the name of the properties of the array object
- [ ] in grip-map.js to represent PropRep objects 
- [ ] in grip.js to represent PropRep objects 
- [ ] in promise.js to represent PropRep objects 

We should rename them to avoid confusion

**Comment by tromey** [comment]
Other spots use `propsArray`, so I will do that.
