### ISSUE TITLE
Review icon used for node reps

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/reps#106]
The icon currently used for node reps can be confusing.

![image](https://cloud.githubusercontent.com/assets/1141550/23514913/088da7d0-ff69-11e6-9224-57f7725a963e.png)

- in the old console this icon acts as an element picker
- in the ruleview and animation inspector, the icon acts as a highlighter

We should settle on one icon for picking elements and one icon for highlighting.

**Comment by nchevobbe** [comment]
_Moved to https://github.com/devtools-html/devtools-core/issues/403_
