### ISSUE TITLE
reps don't show Symbol properties of an object

### ISSUE THREAD

**Issue by tromey** [devtools-html/reps#108]
Try a test case like:

```
const sym = Symbol("hi");

function r6() {
  let x = {};
  x[sym] = 23;
  return x;
}
```

Examining `x` with reps will not show any properties.  However, it should.

This landed in object-inspector: https://github.com/devtools-html/debugger.html/pull/2038

The server side is still pending: https://bugzilla.mozilla.org/show_bug.cgi?id=881480

**Comment by tromey** [comment]
Also, symbols are rendered like `Symbol(hi)` when they are displayed; but I wonder whether quotes would be appropriate in there, like `Symbol("hi")`.  I do think that quotes and escaping should be used when the symbol name is "unusual".

**Comment by nchevobbe** [comment]
> Also, symbols are rendered like Symbol(hi) when they are displayed; but I wonder whether quotes would be appropriate in there, like Symbol("hi"). I do think that quotes and escaping should be used when the symbol name is "unusual".

Filed https://github.com/devtools-html/reps/issues/109 for this

**Comment by nchevobbe** [comment]
_Moved to https://github.com/devtools-html/devtools-core/issues/402_
