### ISSUE TITLE
Use Object inspector for rendered Reps

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/reps#11]
It would allow to dig into an object like it's done in the debugger.
Also, this would be a good experiment to see how to integrate the ObjectInspector in the console.

Specifically, I think that there are some UI challenges when there's multiple Reps on the same line.

**Comment by jasonLaster** [comment]
Yup - also useful for sharing the debugger's Svg util

**Comment by nchevobbe** [comment]
Use it where we show the packet too

**Comment by nchevobbe** [comment]
Okay, so I'm hitting 2 errors : 
```
ERROR in ./src/ObjectInspector.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./utils/Svg in /Users/nicolaschevobbe/Projects/devtools-reps/src
 @ ./src/ObjectInspector.js 6:12-34
```
Since we don't have Svg.js in launchpad, it's obvious that it fail. I guess we should have it in the launchpad, and we can then bump our dependency version number here.
As a quick workaround I can copy the files and assets locally to have the basics working.

```
ERROR in ./src/ObjectInspector.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./Rep in /Users/nicolaschevobbe/Projects/devtools-reps/src
 @ ./src/ObjectInspector.js 7:12-28
```
This one is an easy fix

**Comment by jasonLaster** [comment]
Nice. Yea copy them now and we can then do launchpad.

It's easy to pull core and do yarn sync devtools-launchpad too. But for now
I like the copy pasta approach so we can come up with the right API

**Comment by jasonLaster** [comment]
The ObjectInspector will need a simple redux store for the loadedObjects and an action dispatcher to fetching objects. shouldn't be too hard, but important. 

The other thing is we currently present the data for the objectInspector in scopes.js, but that has all pause data. 

I'll be refactoring all of this for showing watch expression vars. Given this work, I'd be happy to take this issue on and get Object Inspector and the pieces I mentioned into reps!

**Comment by nchevobbe** [comment]
Sure, I'm assigning it to you

**Comment by jasonLaster** [comment]
I want to do a quick update here because the PR is sitting:

This issue was blocked on some P1 issues for the Object Inspector, showing getter properties, bucketing arrays, and properties not being stale while stepping. Everything, but stepping is done. When that lands we can land OI in reps :)

**Comment by nchevobbe** [comment]
_Moved to https://github.com/devtools-html/devtools-core/issues/405_
