### ISSUE TITLE
`copy-assets-watch` does not watch `src/test/mochitest/`

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/reps#123]
`copy-assets` should be call when a test file is modified

**Comment by nchevobbe** [comment]
was I wrong @jasonLaster ?

**Comment by jasonLaster** [comment]
It should symlink the tests because they're not included in the bundle

**Comment by juliandescottes** [comment]
Copy assets behaves differently if you use `--symlink` or not. By default (`--symlink` disabled) the tests are copied to the mozilla-central repository, in which it makes sense to watch the tests folder and trigger a copy.

**Comment by juliandescottes** [comment]
(however since it's not part of the bundle, it can't really use the same mechanism as the one we use right now, which is really tied to the bundling)
