### ISSUE TITLE
Use l10N

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/reps#141]
There are a couple of places where we should use l10N for labels and tooltips.
Let's see what the debugger is doing and if we can do the same.
Any tips @jasonLaster ?

**Comment by jasonLaster** [comment]
Yes.

You have two options:

1. Have a strings.json and properties file with an l10n.js shim (what the
debugger did until recently)

2. Upgrade to the latest launchpad and just use a properties file. The
downside is that I removed the debugger API from the launchpad last month
when I consolidated the devtools-client-adapter. The API should be
published from the debugger, but I'm traveling today. We can talk Monday
when I'm back.

**Comment by jasonLaster** [comment]
After thinking about it a bit more, I don't think it would be hard to upgrade to the newest version of the launchpad. 

The underlying debugger and console clients are available as well as the firefox connection logic. This will let Reps have a simpler client API for console evaluation and in the case of Object Inspector Load Object Properties

**Comment by nchevobbe** [comment]
_Moved to https://github.com/devtools-html/devtools-core/issues/395_
