### ISSUE TITLE
Improve XPathResult display

### ISSUE THREAD

**Issue by nt1m** [devtools-html/reps#144]
See [Bug  1032855 on Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1032855)

**Comment by nchevobbe** [comment]
This needs some work on the Grip, because at the moment we don't have any clue of what's in the XPathResult.

**Comment by nchevobbe** [comment]
_Moved to https://github.com/devtools-html/devtools-core/issues/394_
