### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/reps#62]
Reps repo is lacking documentation / READMEs on the following areas:
- [ ] how to try out the reps demo app
- [ ] how to run the reps tests
- [x] how to publish to mozilla-central
- [ ] some documentation to highlight what is related to the demo application and what is the actual Reps source

**Comment by sole** [comment]
@juliandescottes could you give some rough pointers here please? Maybe me (or other people) could use them to get this running themselves, and improve the docs :)

**Comment by juliandescottes** [comment]
### How to run the demo app
- `yarn install`
- `yarn start`
- go to `localhost:8000` with any browser

You should land on an empty launchpad UI:
<img width="727" alt="image" src="https://cloud.githubusercontent.com/assets/1141550/23414329/d52aecb0-fddb-11e6-9a71-668bc2f22666.png">

- click on Launch Firefox (this should launch firefox with a dedicated profile, listening for connections on port 6080)
- (the UI should update automatically and show you at least one tab for the new firefox instance, it it doesn't, reload the page)

<img width="798" alt="image" src="https://cloud.githubusercontent.com/assets/1141550/23414689/26e459e6-fddd-11e6-861a-dc5cb7582672.png">

- click on any of the tabs, this should open the demo app:
<img width="799" alt="image" src="https://cloud.githubusercontent.com/assets/1141550/23414681/1af67f9c-fddd-11e6-8f80-8c9b5d21e5b7.png">

Then you can type any expression in the input field. They will be evaluated against the target tab selected in the previous steps (so if there specific objects on window on this webpage, you can check how they are represented with reps etc...)

**Comment by juliandescottes** [comment]
### How to publish to mozilla central 

I believe this is already covered by https://github.com/devtools-html/reps/blob/master/RELEASE.md so I'll check this one off the list :)

**Comment by juliandescottes** [comment]
### How to run the reps tests

Reps tests are mochitests (see documentation on MDN: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Mochitest).

They are run on every pull request with Circle CI.
They need a mozilla-central clone to be run locally.

#### A. If you don't have a mozilla-central clone available
- run `bin/prepare-mochitest-dev`, this will create a clone of mozilla central in your repository root folder, under /firefox.
- run `yarn run copy-assets-watch`, this will continuously bundle and copy reps sources to the clone of mozilla central (as well as the tests) when you modify them
- with another command line, cd into /firefox
- run `./mach test devtools/client/shared/components/reps`

#### B. If you already have a mozilla-central clone available
- create a configs/local.json configuration file with the following content:
```
{
  "firefox": {
    "mcPath": "/Path/to/your/mc/clone/"
  }
}
```
- run `yarn run copy-assets-watch`, this will continuously bundle and copy reps sources to the clone of mozilla central (as well as the tests) when you modify them
- with another command line, cd into your mozilla central clone
- run `./mach test devtools/client/shared/components/reps`

**Comment by sole** [comment]
amazinnng! I will incorporate this

**Comment by sole** [comment]
OK, here's the next pull request, this should resolve this issue: https://github.com/devtools-html/reps/pull/116
