### ISSUE TITLE
Kill load-reps

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/reps#89]
We created the load-reps wrapper to ease the transition from "reps in mozilla-central" to "reps bundled from GitHub".

I think it's time to remove this extra layer now that the bundle has landed for some time. This should be done in two parts:
- bug for mozilla-central to update all call-sites (outside of reps/) relying on load-reps
- issue on GitHub to remove load-reps and update reps 

(we might need a new docker image after step1, otherwise the new console tests will fail on circle ci)

Thoughts @nchevobbe @jasonLaster ?

**Comment by nchevobbe** [comment]
Seems good to me. Do you filed the bug in bugzilla ? I can take care of this if not.

**Comment by nchevobbe** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1340806 for the m-c work, feel free to mark it as duplicate if there were already a bug filed.

**Comment by juliandescottes** [comment]
I hadn't filed anything in bugzilla! thanks for doing it.
