### ISSUE TITLE
open-inspector svg bundling issue

### ISSUE THREAD

**Issue by juliandescottes** [devtools-html/reps#94]
When bundling reps, the open-inspector svg is bundled as follows:

"<svg , viewBox=\"0 0 16 16\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M8,3L12,3L12,7L14,7L14,8L12,8L12,12L8,12L8,14L7,14L7,12L3,12L3,8L1,8L1,7L3,7L3,3L7,3L7,1L8,1L8,3ZM10,10L10,5L5,5L5,10L10,10Z\"></path></svg>"

(note the comma after the opening svg tag)
When trying to use it in Firefox, React fails to render it and throws an error.

**Comment by nchevobbe** [comment]
🤔 how weird, I wonder how I managed to get it to work in the Reps tester app.
Si I think the problem come from the svg itself : https://github.com/devtools-html/reps/blob/master/src/reps/images/open-inspector.svg?short_path=ceca2ab ( `<svg width="16", height="16" ...` )
